### ISSUE TITLE
Docker file Error 

### ISSUE THREAD

**Issue by manojsitapara** [paulocorcino/baileys2api#1]
When I tried to run docker file, I was getting following error

> Error: Cannot find module '/home/openwa/production.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by paulocorcino** [comment]
Hi @manojsitapara,
I give you apologize, this docker file it is for use my private project, I already removed of git first to avoid create new doubt, but, I'm doing a new version for general use.

Thank you for appreciating the project.
